version: '3.8'

services:
  web:
    container_name: smart-guardian-web
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      MAP_BOX_TOKEN: pk.eyJ1IjoiYXVicmV5bXV3YWxvIiwiYSI6ImNsdGIxZjVvcTFtdmUybW1zcG9jeHFmYmIifQ.hAa-71IJ_PvPa3S981-syw
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

volumes:
  smart-guardian: